[package]
name = "desmos"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
itertools = "0.13.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serde_with = "3.8.3"
